version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
groups:
  typescript-eslint:
    patterns:
      - "@typescript-eslint/*"
    update-types:
      - "minor"
      - "patch"
